"""Name constant description"""


class NameConstantDesc:
    """Name constant description"""

    NAME = {
        None: "nil",
        True: "true",
        False: "false",
    }


#### CONSTANTS ####
VERSION = "4.0"
TAB = "\t\b\b\b\b"

"""Header"""
HEADER = f"--!native\n--> generated by roblox-py v{VERSION}, artofcoding213's fork\n"
PY_HEADER = f"## generated by roblox-py v{VERSION} ##\nfrom rbx import *\n"
